# Generated by Django 3.2.8 on 2021-11-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomodel',
            name='descricao',
            field=models.TextField(default=None),
        ),
    ]
